version: '3.8'

services:
  nginx:
    image: nginx:latest
    ports:
      - "8080:80"  # Expose port 80 from the container to port 8080 on the host
    volumes:
      - ./html:/usr/share/nginx/html  # Mount the project directory to the NGINX default root
      - ./nginx.conf:/etc/nginx/nginx.conf  # Custom configuration file for NGINX
    restart: unless-stopped


